import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import FirebaseProvider from "@/providers/firebase";
import Header from "@/components/layout/header";
import CurrencyProvider from "@/providers/currency";
import { ToastContainer } from "react-toastify";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Finanças",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CurrencyProvider>
          <div className="bg-neutral-200 min-h-screen pb-4">
            <ToastContainer />
            <Header />

            <FirebaseProvider>{children}</FirebaseProvider>
          </div>
        </CurrencyProvider>
      </body>
    </html>
  );
}
