import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";

import FirebaseProvider from "@/providers/firebase";
import CurrencyProvider from "@/providers/currency";

import Header from "@/components/layout/header";

import "./globals.css";
import TransactionsProvider from "@/providers/transactions";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const runtime = "nodejs";

export const metadata: Metadata = {
  title: "Finanças",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
  icons: {
    icon: "/logo.svg",
    apple: "/logo.svg",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Finanças",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseProvider>
          <CurrencyProvider>
            <TransactionsProvider>
              <div className="bg-neutral-200 min-h-screen h-full pb-4 overflow-hidden">
                <ToastContainer />
                <Header />

                {children}
              </div>
            </TransactionsProvider>
          </CurrencyProvider>
        </FirebaseProvider>
      </body>
    </html>
  );
}
