import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";

import FirebaseProvider from "@/providers/firebase";
import CurrencyProvider from "@/providers/currency";
import CategoriesProvider from "@/providers/categories";

import Header from "@/components/layout/header";

import "./globals.css";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const runtime = "nodejs";

export const metadata: Metadata = {
  title: "Finanças",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseProvider>
          <CurrencyProvider>
            <CategoriesProvider>
              <div className="bg-neutral-200 min-h-screen h-full pb-4 overflow-hidden">
                <ToastContainer />
                <Header />

                {children}
              </div>
            </CategoriesProvider>
          </CurrencyProvider>
        </FirebaseProvider>
      </body>
    </html>
  );
}
